name = "IntervalCensoredEventTimes"
uuid = "31864dbe-68c6-4447-a141-e82f73c554be"
authors = ["Hua Zhou <huazhou@ucla.edu>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
